// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePage(arg1, arg2) {
  return window['go']['main']['Database']['CreatePage'](arg1, arg2);
}

export function InitialiseCanvas(arg1) {
  return window['go']['main']['Database']['InitialiseCanvas'](arg1);
}

export function ListBlocks(arg1) {
  return window['go']['main']['Database']['ListBlocks'](arg1);
}

export function ListPages() {
  return window['go']['main']['Database']['ListPages']();
}

export function LoadMessages(arg1) {
  return window['go']['main']['Database']['LoadMessages'](arg1);
}

export function ProcessTransaction(arg1, arg2) {
  return window['go']['main']['Database']['ProcessTransaction'](arg1, arg2);
}

export function SaveCanvas(arg1, arg2) {
  return window['go']['main']['Database']['SaveCanvas'](arg1, arg2);
}

export function SaveMessages(arg1, arg2) {
  return window['go']['main']['Database']['SaveMessages'](arg1, arg2);
}
