// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePage(arg1:string,arg2:string):Promise<void>;

export function InitialiseCanvas(arg1:string):Promise<any>;

export function ListBlocks(arg1:string):Promise<Array<main.Block>>;

export function ListPages():Promise<Array<main.Page>>;

export function LoadMessages(arg1:string):Promise<string>;

export function ProcessTransaction(arg1:Array<main.Block>,arg2:string):Promise<void>;

export function SaveCanvas(arg1:string,arg2:string):Promise<void>;

export function SaveMessages(arg1:string,arg2:string):Promise<void>;
