// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1:string):Promise<boolean>;

export function GetRelativePath(arg1:string):Promise<string>;

export function GetWorkingDir():Promise<string>;

export function OpenFile(arg1:string):Promise<string>;

export function ReadDir(arg1:string,arg2:boolean):Promise<Array<Record<string, string>>>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
