// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1:string):Promise<string>;

export function ReadDir(arg1:string):Promise<Array<Record<string, string>>>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
